#!/usr/bin/env python

import sys
import os
import datetime
import string
from pprint import pprint

try:
    import json
except ImportError:
    import simplejson as json

import gdata.spreadsheet.service

f = open(os.path.expanduser('~/.b2/schedule.js'), 'r')
config = json.loads(f.read())
f.close()

client = gdata.spreadsheet.service.SpreadsheetsService()
client.ClientLogin(config["user"], config["passwd"])

spread_key = ''
spread_feed = client.GetSpreadsheetsFeed()
for entry in spread_feed.entry:
    if entry.title.text == 'Weekly':
        spread_key = entry.id.text.split('/')[-1]
        break

work_keys = [0, 0]
work_feed = client.GetWorksheetsFeed(spread_key)
today = datetime.date.today()
today_md = "%d.%d" % (today.month, today.day)
tomorrow = today + datetime.timedelta(days=1)
tomorrow_md = "%d.%d" % (tomorrow.month, tomorrow.day)
for entry in work_feed.entry:
    if entry.title.text.split(' ')[1] == today_md:
        work_keys[0] = entry.id.text.split('/')[-1]
    if entry.title.text.split(' ')[1] == tomorrow_md:
        work_keys[1] = entry.id.text.split('/')[-1]
    if work_keys[0] and work_keys[1]:
        break

days = ['Today', 'Tomorrow']
abcup = string.ascii_uppercase
for i, work_key in enumerate(work_keys):
    print days[i]
    cell_feed = client.GetCellsFeed(spread_key, work_key)
    reid = [0, 0]
    todo_column = 0
    for entry in cell_feed.entry:
        if entry.content.text.strip().lower() == 'reid':
            reid = [entry.title.text[0], int(entry.title.text[1:])]
            todo_column = abcup[abcup.find(reid[0])+1]
        elif entry.title.text[0] == todo_column and reid[0]:
            print '    ' + entry.content.text
        elif entry.title.text[0] == reid[0]:
            break
